services:
  - type: web
    name: tx-classify-backend
    env: python
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
