services:
  - type: web
    name: tx-classify-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r pythonHandler/requirements.txt
      python -m spacy download en_core_web_lg
    startCommand: gunicorn pythonHandler.main:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
