services:
  - type: web
    name: tx-classify
    env: python
    buildCommand: |
      cd pythonHandler
      pip install -r requirements.txt
      cd ..
      npm install -g prisma@5.17.0
      export PRISMA_PY_DEBUG_GENERATOR=1
      # Ensure Python client generation
      export SKIP_PYTHON_CLIENT=0
      # Add pythonHandler to PYTHONPATH for Prisma client
      export PYTHONPATH=$PYTHONPATH:/opt/render/project/src/pythonHandler
      cd prisma
      npx prisma@5.17.0 generate
      cd ..
    preDeployCommand: |
      cd prisma
      npx prisma@5.17.0 migrate deploy
      cd ..
    startCommand: cd pythonHandler && gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/pythonHandler
      - key: PRISMA_PY_DEBUG_GENERATOR
        value: "1"
      - key: SKIP_PYTHON_CLIENT
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
