services:
  - type: web
    name: tx-classify
    env: python
    buildCommand: |
      pip install -r pythonHandler/requirements.txt
      npm install -g prisma@5.17.0
      npm install -g @prisma/client@5.17.0
      echo "Checking installed versions:"
      echo "Node.js version: $(node --version)"
      echo "Prisma CLI version: $(npx prisma@5.17.0 --version)"
      echo "Python version: $(python --version)"
      echo "Prisma Python package version: $(python -c "import prisma; print(prisma.__version__)")"
      echo "Setting PYTHONPATH..."
      export PYTHONPATH=$PYTHONPATH:/opt/render/project/src
      echo "PYTHONPATH: $PYTHONPATH"
      echo "Testing import..."
      python test_import.py
      echo "Generating Prisma client..."
      cd prisma
      npx prisma@5.17.0 generate
      cd ..
      echo "Prisma client generated successfully!"
      echo "Testing Prisma..."
      python test_prisma_deploy.py
    startCommand: cd pythonHandler && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PRISMA_PY_DEBUG_GENERATOR
        value: "1"
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
