services:
  - type: web
    name: tx-classify
    env: python
    buildCommand: |
      pip install -r pythonHandler/requirements.txt
      cd pythonHandler
      python init_prisma.py || echo "Prisma initialization failed, but continuing with deployment"
    startCommand: cd pythonHandler && gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
