services:
  - type: web
    name: tx-classify
    env: python
    buildCommand: cd pythonHandler && pip install -r requirements.txt
    startCommand: cd pythonHandler && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true