services:
  - type: web
    name: tx-classify-backend
    env: python
    # buildCommand and startCommand will be executed from within the 'pythonHandler' directory
    # if 'Root Directory' is set to 'pythonHandler' in the Render UI.
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt  # Path is now relative to 'pythonHandler'
      python -m spacy download en_core_web_lg
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120 # Path is now relative to 'pythonHandler'
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PYTHONPATH
        value:
          /opt/render/project/src # Repo root, allows finding pythonHandler if needed by external scripts, or main if start is pythonHandler.main
          # If Root Dir is pythonHandler, and start is main:app, this might not be strictly needed for Gunicorn
          # but can remain for broader compatibility.
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
