type Expenses {
  date: Date!
  description: String
  debitAmount: Float
  creditAmount: Float
  category: Categories!
}

type Categories {
  name: String
  expenses: [Expenses!]!
}

type Query {
   allExpenses: [Expenses!]
}
