services:
  - type: web
    name: tx-classify-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: BACKEND_API
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT
        sync: false
    healthCheckPath: /
    autoDeploy: true